# Use a imagem oficial do Traefik
FROM traefik:v2.5

# Copie os arquivos de configuração para dentro do contêiner
COPY traefik.yml /etc/traefik/traefik.yml
COPY traefik_auth /etc/traefik/traefik_auth
